// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EJournal.Database;

[Table("groups", Schema = "ejournal")]
public partial class Group
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("admission_year")]
    public int? AdmissionYear { get; set; }

    [Column("name", TypeName = "character varying")]
    public string Name { get; set; }

    [Column("specialty")]
    public int? Specialty { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<Import> Imports { get; } = new List<Import>();

    [ForeignKey("Specialty")]
    [InverseProperty("Groups")]
    public virtual Specialty SpecialtyNavigation { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<Student> Students { get; } = new List<Student>();

    [InverseProperty("Group")]
    public virtual ICollection<Subject> Subjects { get; } = new List<Subject>();
}