// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EJournal.Database;

[PrimaryKey("GroupId", "Year")]
[Table("imports", Schema = "ejournal")]
public partial class Import
{
    [Key]
    [Column("group_id")]
    public int GroupId { get; set; }

    [Key]
    [Column("year")]
    public int Year { get; set; }

    [Column("link", TypeName = "character varying")]
    public string Link { get; set; }

    [Column("last_import", TypeName = "timestamp without time zone")]
    public DateTime? LastImport { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("Imports")]
    public virtual Group Group { get; set; }
}