// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EJournal.Database;

[Table("lessons", Schema = "ejournal")]
public partial class Lesson
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("subject_id")]
    public int? SubjectId { get; set; }

    [Column("date")]
    public DateOnly? Date { get; set; }

    [Column("note", TypeName = "character varying")]
    public string Note { get; set; }

    [Column("theme", TypeName = "character varying")]
    public string Theme { get; set; }

    [InverseProperty("Lesson")]
    public virtual ICollection<Mark> Marks { get; } = new List<Mark>();

    [ForeignKey("SubjectId")]
    [InverseProperty("Lessons")]
    public virtual Subject Subject { get; set; }
}