// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EJournal.Database;

[Table("specialties", Schema = "ejournal")]
public partial class Specialty
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("code", TypeName = "character varying")]
    public string Code { get; set; }

    [Column("name", TypeName = "character varying")]
    public string Name { get; set; }

    [InverseProperty("SpecialtyNavigation")]
    public virtual ICollection<Group> Groups { get; } = new List<Group>();
}