// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EJournal.Database;

[Table("students", Schema = "ejournal")]
public partial class Student
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("first_name", TypeName = "character varying")]
    public string FirstName { get; set; }

    [Column("middle_name", TypeName = "character varying")]
    public string MiddleName { get; set; }

    [Column("last_name", TypeName = "character varying")]
    public string LastName { get; set; }

    [Column("group_id")]
    public int? GroupId { get; set; }

    [Column("budget")]
    public bool? Budget { get; set; }

    [Column("birthday")]
    public DateOnly? Birthday { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("Students")]
    public virtual Group Group { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<Mark> Marks { get; } = new List<Mark>();
}