// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EJournal.Database;

[Table("teachers", Schema = "ejournal")]
public partial class Teacher
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("first_name", TypeName = "character varying")]
    public string FirstName { get; set; }

    [Column("middle_name", TypeName = "character varying")]
    public string MiddleName { get; set; }

    [Column("last_name", TypeName = "character varying")]
    public string LastName { get; set; }

    [Column("contact_info", TypeName = "character varying")]
    public string ContactInfo { get; set; }

    [Column("birthday")]
    public DateOnly? Birthday { get; set; }

    [InverseProperty("Teacher")]
    public virtual ICollection<Subject> Subjects { get; } = new List<Subject>();
}